providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python3", "nodejs_20"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build:css",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn mysite.wsgi --bind 0.0.0.0:$PORT --log-file -"